### ISSUE TITLE
25B Flowcell

### ISSUE THREAD

**Issue by brantfaircloth** [nickp60/fcid#1]
Really handy tool - thanks!  I've been using the 10x code for a long time to help ID different instruments/flowcells, but it has not been updated since their linked reads bit the bullet.  Anyway, I have some recent data from a 25B flowcell and wanted to let you know the FCID for that run was:

`2252NYLT4`

-b

**Comment by nickp60** [comment]
@brantfaircloth I heard back from the Illumina folks and just pushed some changes to reflect them:  the 10B kit ones should be ending in LT3 and the 25B should be LT4.  Thanks again!
